#email to which errors will be sent
email: "your_email@domain"
#Location of the config file for barcodeIdentification
bID: "./config.txt"
#Location of the samples json file produced with fastq2json.py script
samples: "./samples.json"
#output directory
output_dir: ""
#Currently "mm10" and "hg38" available
assembly: "mm10"
#Number of barcodes used
num_tags: "5"

#Hisat2 indexes location with prefix
hisat2_index:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/GRCm38.p6"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/GRCh38"
hisat2_splice_sites:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/Mus_musculus.GRCm38.95.ss"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/Homo_sapiens.GRCh38.97.ss"
#Annotation GTF file used for featureCounts
anno_gtf:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/GRCm38.p6.annotation.gtf.gz"
    hg19: "/groups/guttman/genomes/homo_sapiens/hg19/STAR/hg19/gencode.v19.annotation.gtf"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/Homo_sapiens.GRCh38.97.gtf.gz"
#Annotation GTF file used for featureCounts
anno_gtf:
    mm10: "/groups/guttman/Peter/genomes/GRCm38.p6/GRCm38.p6.annotation.gtf.gz"
    hg19: "/groups/guttman/genomes/homo_sapiens/hg19/STAR/hg19/gencode.v19.annotation.gtf"
    hg38: "/groups/guttman/Peter/genomes/GRCh38/Homo_sapiens.GRCh38.97.gtf.gz"
